repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        fail_fast: true
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: requirements-txt-fixer
      - id: no-commit-to-branch
        args: ['--branch', 'main']

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        types: [python]
        language: python
        language_version: python2.7
        additional_dependencies: [pylint==1.9.5, mock==3.0.5, pytest==4.6.11]
        args: [
            "-sn", # Don't display the score
            "--rcfile=.pylintrc", # Link to your config file
          ]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
        stages: [manual, push]
